# Generated by Django 4.2.11 on 2024-05-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_video", models.FileField(upload_to="videos/")),
                (
                    "output_video",
                    models.FileField(
                        blank=True, null=True, upload_to="processed_videos/"
                    ),
                ),
            ],
        ),
    ]
